---
title: "Introduction to amplicon sequencing analysis and genomic surveillance"
author: "Paulo Manrique"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of this repository is to introduce researchers in the analysis of genotyping information generated through amplicon sequencing (also called Microhaplotype genotyping).

This covers 4 tutorials:

- [Intro to R](https://paulonvnv.github.io/intro_to_genomic_surveillance/Intro_to_R.html),
- [Performance of amplicon sequencing data](https://paulonvnv.github.io/intro_to_genomic_surveillance/Sequencing_PErformance.html),
- [Drug Resistance Surveillance](https://paulonvnv.github.io/intro_to_genomic_surveillance/Drug_resistance_surveillance.html),
- [Complexity of Infection](https://paulonvnv.github.io/intro_to_genomic_surveillance/Complexity_of_infection.html)

This GitHub repository contains a set of functions that allows the user to upload and manipulate the genotypic information stored in .tsv tables (in Seudo-CIGAR format) that has been generated by the [malaria-amplicon-pipeline](https://github.com/broadinstitute/malaria-amplicon-pipeline) of our lab. All those functions and the required libraries are in the R scripts [amplseq_functions.R](https://github.com/Paulonvnv/intro_to_genomic_surveillance/blob/main/docs/functions_and_libraries/amplseq_functions.R) and [amplseq_required_libraries.R](https://github.com/Paulonvnv/intro_to_genomic_surveillance/blob/main/docs/functions_and_libraries/amplseq_required_libraries.R), and an additional set of Rcpp functions for the estimation of IBD and eigenvectors are in the files [hmmloglikelihood.cpp](https://github.com/Paulonvnv/MHap-Analysis/blob/main/docs/functions_and_libraries/hmmloglikelihood.cpp) and [Rcpp_functions.cpp](https://github.com/Paulonvnv/intro_to_genomic_surveillance/blob/main/docs/functions_and_libraries/Rcpp_functions.cpp). Some of the functions require additional input files such as fasta files for reference strains or tables of alleles associated with drug resistance. These additional information is stored in the folder [`doc/reference`](https://github.com/Paulonvnv/intro_to_genomic_surveillance/tree/main/docs/reference).

